export const ROUTES = {
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  COMPANIES: '/companies',
  EMPLOYEES: '/employees',
  DRIVERS: '/drivers',
  VEHICLES: '/vehicles',
  BOOKINGS: '/bookings',
  TRIPS: '/trips',
  FUEL: '/fuel',
  MAINTENANCE: '/maintenance',
  EXPENSES: '/expenses',
  DOCUMENTS: '/documents',
  REPORTS: '/reports',
  SETTINGS: '/settings',
  PROFILE: '/profile',
  NOT_FOUND: '/404',
  FORBIDDEN: '/403',
  SERVER_ERROR: '/500',
};